name: Codecov check

on:
  push:
    branches:
      - main
    paths:
      - nonebot_plugin_strman/**
      - tests/**

jobs:
  codecov:
    name: Codecov check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3

      - name: Install dependencies
        run: |
          poetry install

      - name: Generate coverage report
        run: |
          poetry add --dev pytest-cov
          poetry run pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
