name: Static code check

on:
  pull_request:
    paths:
      - nonebot_plugin_strman/**

jobs:
  pylint:
    name: pylint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3

      - name: Install dependencies
        run: |
          poetry install

      - uses: dciborow/action-pylint@0.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning

  pyright:
    name: pyright check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: abatilo/actions-poetry@v2.1.3
        run: |
          poetry install

      - uses: jordemort/action-pyright@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          lib: true
