name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish
        uses: JRubics/poetry-publish@v1.8
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          allow_poetry_pre_release: "yes"
