name: Unit test

on:
  pull_request:
    paths:
      - nonebot_plugin_strman/**
      - tests/**

jobs:
  unittest:
    name: Unit test
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3

      - name: Install dependencies
        run: |
          poetry install

      - name: Run unit tests
        run: |
          poetry run pytest
